### ISSUE TITLE
template not found

### ISSUE THREAD

**Issue by biba79** [pyladies/pyladies#139]
I get this:

    $ mynt gen -f _site
    >> Parsing
    >> Processing
    >> Rendering
    !! Template not found.
    ..  post.html in post 'Donate to PyLadies @ PyCon 2015!'

**Comment by econchick** [comment]
Are you doing it within the `www` directory?

**Comment by biba79** [comment]
Yes, and this is what happens in it... 

    source envs/pyladies/bin/activate    
    cd pyladies/www
    www beec79$ mynt gen -f _site && mynt serve _site
    >> Parsing
    >> Processing
    >> Rendering
    !! Template not found.
    ..  post.html in post 'Donate to PyLadies @ PyCon 2015!'

    www beec79$ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.

    nothing to commit, working directory clean
    
    www beec79$ git remote -v
    origin	https://github.com/pyladies/pyladies.git (fetch)
    origin	https://github.com/pyladies/pyladies.git (push)
    
    www beec79$ git pull
    remote: Counting objects: 55, done.
    remote: Compressing objects: 100% (48/48), done.
    remote: Total 55 (delta 26), reused 15 (delta 6)
    Unpacking objects: 100% (55/55), done.
    From https://github.com/pyladies/pyladies
    fafcd1a..fac4603  master     -> origin/master
    Updating fafcd1a..fac4603
    Fast-forward
    README.md                                          |   2 +-
    www/_assets/images/pyladies_australia.png          | Bin 0 -> 21354 bytes
    .../2014-11-02-fundraising-for-pycon-2015.md       |  75 +++++++++++++++++++++
    www/_templates/site.html                           |   6 +-
    www/about/index.html                               |   2 +-
    www/config.yml                                     |  67 ++++++++++++++++++
    www/locations/index.html                           |  24 +++++--
    7 files changed, 163 insertions(+), 13 deletions(-)
    create mode 100644 www/_assets/images/pyladies_australia.png
    create mode 100644 www/_posts/2014-11-02-fundraising-for-pycon-2015.md
    www beec79$ mynt gen -f _site && mynt serve _site
    >> Parsing
    >> Processing
    >> Rendering
    !! Template not found.
    ..  post.html in post 'Donate to PyLadies @ PyCon 2015!'
   
    www beec79$ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.

    nothing to commit, working directory clean
   
    www beec79$ mynt gen -f _site
    >> Parsing
    >> Processing
    >> Rendering
    !! Template not found.
    ..  post.html in post 'Donate to PyLadies @ PyCon 2015!'
   
    www beec79$ ls
    CodeOfConduct		about			index.html
    _assets			archives		locations
    _deploy_example.sh	blog			resources
    _posts			config.yml		sponsor
    _templates		feed.xml

    www beec79$ ls
    CodeOfConduct		about			index.html
    _assets			archives		locations
    _deploy_example.sh	blog			resources
    _posts			config.yml		sponsor
    _templates		feed.xml
 
    www beec79$ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.

    nothing to commit, working directory clean

    www beec79$ ls
    CodeOfConduct		about			index.html
     _assets			archives		locations
    _deploy_example.sh	blog			resources
    _posts			config.yml		sponsor
    _templates		feed.xml
    www beec79$ pwd
    /Users/beec79/pyladies/www

**Comment by econchick** [comment]
I can't reproduce this error - your error is complaining that `_templates/post.html` doesn't exist but it does ([here](https://github.com/pyladies/pyladies/blob/master/www/_templates/post.html)).

Perhaps try removing the whole repo, recloning and making a new env.

**Comment by econchick** [comment]
If this is still happening, please reopen. Thanks!

**Comment by econchick** [comment]
My bad - this was indeed replicated.  Fixed with c994205b2533ba62e89f9531ac9400613bf5fa82

**Comment by biba79** [comment]
Cool. We've pushed the munich page a different way and since you approved pull request it's been up and running just fine. Thanks for the help.
