### ISSUE TITLE
Fourth-level headings are in Arial/Helvetica

### ISSUE THREAD

**Issue by hynek** [pyladies/pyladies#147]
As exemplified in http://www.pyladies.com/blog/pyladies-at-pycon/ by the “PYLADIES GPG KEY SIGNING OPEN SPACE” heading:

![image](https://cloud.githubusercontent.com/assets/41240/6787949/7178908c-d196-11e4-8c51-7335425b2796.png)

**Comment by econchick** [comment]
Finally fixed!
