### ISSUE TITLE
Make site flex-width/mobile-friendly

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#148]
Currently when you resize the page, the navigation bar awkwardly resizes:
![2015-04-13 at 7 31 am](https://cloud.githubusercontent.com/assets/1191069/7114811/3bda5b80-e1af-11e4-9aab-bf24bc8f2ba0.png)

Maybe we also need to collapse the navbar into fewer items (and maybe replace the logo with the smal geek girl.

It also isn't mobile friendly - navbar should collapse into the "hamburger" icon.

**Comment by TheInvincible** [comment]
I see this is still an issue. I would like to take it on.
