### ISSUE TITLE
Collection of CfPs relevant to PyLadies

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#152]

**Comment by econchick** [comment]
Should also think about a good process for maintaining & collecting

**Comment by econchick** [comment]
Thinking more on this - I think a YAML file would be sufficient and easy enough to update & maintain of upcoming Python/OSS-centric conferences that the static site parser automatically picks up (similar to how the locations are currently generated)

**Comment by willingc** [comment]
Let's put together a set of links where sites aggregate upcoming conferences.
