### ISSUE TITLE
Promote PyLadies speakers at upcoming conferences

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#153]

**Comment by yasoob** [comment]
Should we setup a public `yml`/`md` list? I don't think having a mailing list would be feasible as only a single/few person/s would have access to them that way and others couldn't benefit from it.

Just my 2 cents.

**Comment by econchick** [comment]
Wasn't suggesting a mailing list, but it as a way to promote those speaking.  I'd imagine similar setup to our `www/config.yml` with the listing of speakers, and then a template pulling from that.

But this needs further discussion on the pyladies organizers' list as to if we should do it, or not.

**Comment by yasoob** [comment]
Yes. It would need a proper discussion. Many people are reluctant to list their emails publicly.
