### ISSUE TITLE
Write up: how to add a resource to pyladies site

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#155]
Create a form where folks can submit resources they like

**Comment by ceaess** [comment]
Is this a simple e-mail form, or are you hoping to stick the resources in some kind of queue for approval?

**Comment by econchick** [comment]
@ceaess nothing too complex; could even be just a Google form. Is this something you'd like to work on?

**Comment by ceaess** [comment]
@econchick I'd be happy to. Would you prefer a google form for the spreadsheet management? If so, is there a Pyladies organization on Google under which I should create the form?

**Comment by econchick** [comment]
@ceaess yeah, we do. I've created a "shared" folder and give your gmail address edit access to it - let me know if there's any issue!

**Comment by ceaess** [comment]
@econchick Fantastic, I seem to have the access I need. I'll create a PR to add a link to the form on the resources index page when everything's ready, if that sounds good?

**Comment by econchick** [comment]
perfect, thank you!
