### ISSUE TITLE
Cleaning up website

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#156]
Ideas:
- [ ] carousel of photos from local groups above the fold
- [ ] move down "signup for newsletter"
- [ ] remove/retire "forum" which points to discuss.pyladies.com
- [ ] replace "forum" with contact info landing page
- [ ] for "Resources", have the "list view" actually show a landing page of links to resources (see: @cwilling's CPython groovy landing page)
- [ ] new color scheme: light blue/navy (perhaps adapt with the bootstrap theme)
- [ ] pyladies geek as a favicon instead of the python logo

What else? add comments!

**Comment by econchick** [comment]
Here's the [color scheme](http://www.colourlovers.com/palette/3730203/PyLadies) that I'd suggest (but am more than open to talk about and adjust).

**Comment by econchick** [comment]
Here's the AI for the pyladies logo: https://www.dropbox.com/s/fub4ms919xlvkdp/pycon-banner-2015.ai?dl=0

**Comment by williln** [comment]
I like this color scheme! I am also not a designer :) I would be willing to help with all this, but would need some strong mentoring.

**Comment by econchick** [comment]
Thanks @williln ! This is actually being worked on at [pyladies/pyladies-theme](github.com/pyladies/pyladies-theme) with @viviangb - she needs to push what she has (is currently at Uni and quite busy).  I've just invited her to the Collaborators team so I can assign her this issue; but I am sure she'd welcome help (will assign it to you, too).

**Comment by viviangb** [comment]
Hello @williln @econchick , I apologize for the long delay but I finally finished my school work so I'm back again with this project. I'll be pushing my changes this weekend because first I need to clean it up a bit. @williln what are your skills? If you want to help, I'm currently redesigning the pyladies site using this framework, http://getuikit.com, please take a look at it whenever you can.

**Comment by williln** [comment]
@viviangb I've done mostly Django for web development, and am not familiar with this framework. But I'm a fast learner! I also have incredibly minimal design experience. 

I basically hopped on this issue because it sounded cool and I want to be more involved in contributing to Pyladies :)
