### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#157]
Update the `CONTRIBUTING.md` file to add that any unassigned issue is fair game!

**Comment by williln** [comment]
Here? https://github.com/pyladies/pyladies/blob/master/CONTRIBUTING.md

You mean like add a new section about contributing to the repo (basically, like what I am doing now? :) ) 

I'll do this too!

**Comment by econchick** [comment]
Yep exactly!

**Comment by econchick** [comment]
I think that in order to assign issues, one has to be a part of the [PyLadies Contributor team](https://github.com/orgs/pyladies/teams/contributors); can you add a blurb about that too, @williln ? I am not sure how people can request to join; I'm not sure if it's even public :-/
