### ISSUE TITLE
Vagrant setup for dev?

### ISSUE THREAD

**Issue by phildini** [pyladies/pyladies#159]
Hello! Since there are special requirements for setting up a devenv, would it make sense to have a Vagrantfile that people could use to bootstrap a developer environment? If so, I'm happy to make one.

**Comment by econchick** [comment]
Thanks @phildini !  Let's confirm that this is needed in a VM before we update the README and provide a vagrant setup :+1:

**Comment by econchick** [comment]
FYI So far, python-dev was required when I spun up a fresh VM.  Not sure about libevent-dev.

**Comment by phildini** [comment]
Yeah, it may not be a priority if a python static site generator is all that's really needed. I'm happy closing the issue since mynt is now running fine for me.
