### ISSUE TITLE
Issues generating site

### ISSUE THREAD

**Issue by phildini** [pyladies/pyladies#162]
In trying to check requirements.txt for any dependency orphans, I came across a bug where I wasn't able to generate the site. 

Steps to Reproduce (all of these are on MacOSX Yosemite): 

1. Clone pyladies repo
2. Create virtualenv
3. `pip install mynt==0.2.2`
4. `cd www && mynt gen _site`

Error: 
```
>> Parsing
>> Processing
>> Rendering
!! Template not found.
..  post.html in post 'A PyLadies-packed PyCon 2015'
```

**Comment by econchick** [comment]
Addressed with c994205b2533ba62e89f9531ac9400613bf5fa82
