### ISSUE TITLE
Create a hub for remote women

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#163]
Using DC's model, publish upcoming classes that are recorded/broadcasted.

**Comment by econchick** [comment]
Add a resource page in the organizers' manual on how to organize a good remote class (cc @kcunning)

**Comment by williln** [comment]
also cc @ossanna16; I know she was thinking about this as well.

**Comment by ossanna16** [comment]
Thanks for thinking of me Lacey :) Lynn and I talked about the publishing part and I'm working on it.

**Comment by KatherineMichel** [comment]
I'm going to be doing a PyLadies Remote talk eventually and perhaps could help a bit with this if it's still in the works.

**Comment by kcunning** [comment]
@KatherineMichel There is a hub for remote learners!

http://remote.pyladies.com/index.html

**Comment by KatherineMichel** [comment]
Thank you, that's good to know @kcunning.
