### ISSUE TITLE
Add links to our store!

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#164]
We currently have [pyladies.spreadshirt.com](http://pyladies.spreadshirt.com) and we should link to it!

We also have a sticker store with [stickermule](https://www.stickermule.com/user/1070441144/stickers).

**Comment by williln** [comment]
@econchick I'll do this. Can you assign it to me? 

Also, where should this go? I was thinking on the homepage, under "WELCOME!" Maybe add a section called, "GET SOME SWAG!" with links to the two stores?

**Comment by econchick** [comment]
Maybe under the "Sponsor Us" button on the right, like two buttons, "Buy our stickers" and "Check out our swag" (really don't care about the verbiage though).

Feel free to take it - I'm going to make a new team within the organization for "contributors" and assign it to you.

**Comment by econchick** [comment]
@williln I just sent you an invite to the Collaborators team - accept it so I can try to add you to this and the other issue :)

**Comment by williln** [comment]
Done! :)

**Comment by williln** [comment]
@econchick Stupid question time: how do I install libevent? I downloaded the GZ file, but pip install doesn't seem to like it. (I'm used to developing in a very consistent, but sort of odd environment-- this is my first time setting up a GitHub project to run locally on my machine.) 

Or if anyone else has a "getting Pyladies running on your machine" that is more step-by-step in terms of installing this particular header, I'd love to see it.

**Comment by econchick** [comment]
yeah it's not a Python library. I think this is what's needed to install it:

* Download latest stable release of libevent from their site.
* Unzip and cd into the libevent directory
* Run `./configure && make`
* Run `sudo make install`

**Comment by econchick** [comment]
(also - there are no stupid questions!)

**Comment by willingc** [comment]
@econchick +1 re: questions :)
@williln Ooh links to the stores. :cool:

**Comment by williln** [comment]
New question time! I'm still trying to get Pyladies to run locally on my machine, and am almost there. I am to  step 6: 

> 6. (PyLadies) $ ```mynt gen -f _site && mynt serve _site```

But I'm getting an ImportError: 
> ```  File "/Users/laceywilliamshenschel/pyladies/pyladies/lib/python3.4/site-packages/mynt/server.py", line 5, in <module>
    from SimpleHTTPServer import SimpleHTTPRequestHandler
ImportError: No module named 'SimpleHTTPServer'```

As far as I could tell, things installed correctly when I ran step 4 (requirements.txt). But it did produce many many lines of messages, and then ended with

> ```Successfully installed Jinja2-2.7 PyYAML-3.11 Pygments-2.0.2 argh-0.26.1 houdini.py-0.1.0 markupsafe-0.23 misaka-1.0.2 mynt-0.2.3 pathtools-0.1.2 watchdog-0.8.3```

No rush on helping me with this, but I'd really like to successfully get the site running locally so I can learn to do neat stuff :)

**Comment by estherbester** [comment]
Hi @williln SimpleHTTPServer is in the standard lib, but it looks like it was renamed in Python 3 to http.server, per this -  https://docs.python.org/2/library/simplehttpserver.html 

I'm not a Python 3 user so I can't be of any more help, I'm afraid. Is mynt Python 3-compatible?

**Comment by econchick** [comment]
I don't think it is; and also make sure you're in the `www` directory or mynt won't work.

**Comment by williln** [comment]
I think that's the problem; that I'm using python 3. I'll install
2....7?... tomorrow and try again. Thanks!

**Comment by williln** [comment]
I am finally getting back to this... 

![screen shot 2015-06-02 at 6 06 30 pm](https://cloud.githubusercontent.com/assets/2286304/7950598/21f20f0e-0952-11e5-8943-eab5f7ae57ab.png)

I am not a CSS wizard, but I would like to center the text on at least the bottom button. There are a lot of places where the CSS impacts these buttons, though. For CSS, I created an id called ```#swag_btn``` and ```#stickers_btn``` and just added that everywhere in the CSS that ```#sponsor_us_btn``` appeared in screen.css. I am not sure why the text isn't centered. I added a ```text-align: center``` and that didn't help. 

Any tips?

**Comment by willingc** [comment]
@williln If you send me a link to the code you are working on or submit a work in process PR here, I would be happy to take a look.

**Comment by willingc** [comment]
@audreyr Your Inland Empire post last night got me thinking... Any tips for @williln?

**Comment by audreyr** [comment]
@williln Try generating the styles with http://howtocenterincss.com and see if it works :)

If still stuck, don't worry. If needed I'll take a closer look at the code when I get a chance.

**Comment by willingc** [comment]
Thanks @audreyr. That is a cool site :)

**Comment by williln** [comment]
@willingc and @audreyr I got it to work with the site that Audrey linked to (well, with inline styles, which is not ideal, but at least fine for an in-progress PR), but now I cannot git push because of this error: 

``` 
error: failed to push some refs to 'git@github.com:williln/pyladies.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I ran ```git pull --rebase upstream master``` before I started today, so I'm not sure what this means. I tried to run ```git pull``` like the error message suggested, but then I got this error: 

``` 
E325: ATTENTION
Found a swap file by the name "~/pyladies/.git/.MERGE_MSG.swp"
          owned by: laceywilliamshenschel   dated: Sat Jun 13 12:44:14 2015
         file name: ~laceywilliamshenschel/pyladies/.git/MERGE_MSG
          modified: no
         user name: laceywilliamshenschel   host name: adms-894236.local
        process ID: 17261 (still running)
While opening file "/Users/laceywilliamshenschel/pyladies/.git/MERGE_MSG"
             dated: Sat Jun 13 12:46:46 2015
      NEWER than swap file!

(1) Another program may be editing the same file.
    If this is the case, be careful not to end up with two
    different instances of the same file when making changes.
    Quit, or continue with caution.

(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r /Users/laceywilliamshenschel/
pyladies/.git/MERGE_MSG"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/Users/laceywilliamshenschel/
pyladies/.git/.MERGE_MSG.swp"
    to avoid this message.
-- More --
``` 

HALP! (I don't use git for my work, so I'm still very much a Git newbie, and feel like I encounter a new git error every time I do this. Which is how you learn, but is also super annoying and part of why this very simple project is taking me so long. :-/ )

**Comment by williln** [comment]
So I got the styles to work (as inline styles, which is not ideal, but which is fine for an in-process PR), but now I cannot push them to my repo because of this error: 

``` 
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:williln/pyladies.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
``` 

I have run ```git pull --rebase upstream master``` with no errors, and I have committed with no errors, but whenever I try to run ```git pull``` like it suggests, I get this:

**Comment by williln** [comment]
I did it!
