### ISSUE TITLE
Upcoming meetups not appearing in sidebar 

### ISSUE THREAD

**Issue by williln** [pyladies/pyladies#169]
In Firefox and Chrome, the Upcoming Meetups box is blank. 

![upcoming_meetups](https://cloud.githubusercontent.com/assets/2286304/7446683/dd5bd88a-f195-11e4-933f-ef717b4c0221.png)

**Comment by willingc** [comment]
@williln Well that's unfortunate. Any idea why? Recent PR change? Meetup issue?

**Comment by willingc** [comment]
@williln Oh and nice job on the recent PRs :)

**Comment by williln** [comment]
@willingc No idea, just happened to notice it. There is this notice in the meetup API Google group that has a reported issue that says it's fixed, so idk. :-/ 

And thanks!

**Comment by econchick** [comment]
hmm I don't know when the last time it worked (could be yesterday, could be 3 months ago, no idea).  IIRC it's a Meetup widget, e.g. not something we wrote ourselves.  Worth investigating.

**Comment by willingc** [comment]
Wondering if the recent pr merge with config.yml had something to do with it. Nothing jumped out at me but another pair of eyes couldn't hurt.

**Comment by willingc** [comment]
I think this may be related to it: https://groups.google.com/forum/?fromgroups#!topic/meetup-api/4gki83Icrjo

**Comment by willingc** [comment]
And if that's not it there was a recent Oauth bug that meetup fixed in their code.

**Comment by willingc** [comment]
This is the file for meetup widget:
https://github.com/pyladies/pyladies/blob/master/www/_assets/js/meetup_widget.js

The developer tools in Chrome were showing an error with the data length in the for loop having an undefined error.

**Comment by econchick** [comment]
Fixed with #174
