### ISSUE TITLE
Create a San Diego PyLadies website

### ISSUE THREAD

**Issue by willingc** [pyladies/pyladies#187]
@piinthecloud Would you mind if San Diego PyLadies used the very nicely done Seattle site as a starting point for creating the San Diego PyLadies website? With attribution of course :)

**Comment by piinthecloud** [comment]
Hi Carol, yeah, please go ahead :)

On Thu, Jun 18, 2015 at 11:15 AM, Carol Willing <notifications@github.com>
wrote:

> @piinthecloud <https://github.com/piinthecloud> Would you mind if San
> Diego PyLadies used the very nicely done Seattle site as a starting point
> for creating the San Diego PyLadies website? With attribution of course :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyladies/pyladies/issues/187>.
>



-- 
Cheers,

Stephanie Pi

**Comment by willingc** [comment]
@piinthecloud Awesome! I showed it to some folks here in San Diego and they really liked it. We're hoping to have it as a Tuesday Night project for some of our newer coders.

**Comment by willingc** [comment]
@econchick Ooh...I like the location-specfic label :)
