### ISSUE TITLE
Add more content to Pyladies London site

### ISSUE THREAD

**Issue by Winterflower** [pyladies/pyladies#195]
@galvanic @Eleonore9 what do you think?

**Comment by Eleonore9** [comment]
That's a great idea! I think @galvanic need to add you as a contributor, but all ideas & contributions are welcome!

**Comment by galvanic** [comment]
Hey @Winterflower the repo for the pyladies LDN is here: https://github.com/pyladieslondon/pyladieslondon.github.io 

I'm happy adding you as a contributor or you can add a PR, whichever you prefer.

**Comment by Winterflower** [comment]
@galvanic thanks, that would be awesome!
