### ISSUE TITLE
Circle CI deployments not working

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#200]
For some reason, Circle CI will not actually deploy merged commits (although it **does** look like it's successful, see [recent build](https://circleci.com/gh/pyladies/pyladies/31)).  I have no idea what's the issue here.

**Comment by willingc** [comment]
@econchick Did the latest merged commits get deployed? Or is this still an issue?

**Comment by econchick** [comment]
@willingc I don't think it's resolved; I've been manually deploying for the time being.  The deploys I did this morning, I didn't even check to see if it worked because I assumed it didn't.  But for the next one, I'll be sure to pay attention.

**Comment by econchick** [comment]
@willingc I just tried with #197 and Circle CI didn't work even though it looks like it had ([log](https://circleci.com/gh/pyladies/pyladies/44)). :-/

**Comment by willingc** [comment]
@econchick Good to know. Will take a look at the log.

**Comment by willingc** [comment]
@econchick See notes on #205

**Comment by estherbester** [comment]
The build step is currently failing (failed on merging #295). 

Right now the error is `ImportError: No module named six.moves`. As far as I can tell, two quick-fix options are 1)  upgrade the version of pip or 2) build on Ubuntu 14 rather than 12.04.

**Comment by willingc** [comment]
@estherbester I would do 1 and 2 ;-)

**Comment by estherbester** [comment]
Ok. I tried changing the build image to Ubuntu 14, but then it breaks on fab deploy with `ImportError: No module named Crypto`, so I changed it back to Ubuntu 12.04. 

I am not certain where the step to upgrade pip should take place. I am wary of adding it as a pre-dependency command because it comes after the virtualenv is created. 

This is fun!  😛

**Comment by willingc** [comment]
Hmm...I wonder if we used Travis if it would be more straightforward.

**Comment by estherbester** [comment]
So the build and deploy commands now work (thanks @willingc!!), but the problem remains that while Circle believes the deployment happened, the site has not actually been updated 😹

**Comment by estherbester** [comment]
Ok I think I see the problem but I'm afraid to try it without a good rollback - I believe the rsync command in the fabfile needs to be set with `local=_site/` (note the trailing slash). Let me test a bit more

**Comment by willingc** [comment]
Can we set up a staging site for testing?

**Comment by estherbester** [comment]
Went ahead and merged PR #304, because YOLO, and it worked
