### ISSUE TITLE
Setup a sub-domain to point to our server's IP address

### ISSUE THREAD

**Issue by amacbee** [pyladies/pyladies#221]
We are creating a PyLadies Tokyo website using WordPress on our VPN server.
If possible, we want to setup a sub-domain (e.g. tokyo.pyladies.com) to point to our server's IP address.

Could anyone prepare a sub-domain?
Who should we ask that of?

**Comment by econchick** [comment]
I can definitely help with that. Let me know the IP address and I'll set it up!

**Comment by amacbee** [comment]
Thank you!
Here is our server's IP address: 157.7.205.20

And, please merge #219 pull request.

**Comment by econchick** [comment]
@amacbee I just added the DNS record - it may take up to 24 hours to have it work.

So sorry I haven't addressed your PR - will do that now!

**Comment by econchick** [comment]
@amacbee FYI I see that it propagated (for me at least):

```bash
$ dig tokyo.pyladies.com

; <<>> DiG 9.8.3-P1 <<>> tokyo.pyladies.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34734
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;tokyo.pyladies.com.		IN	A

;; ANSWER SECTION:
tokyo.pyladies.com.	10799	IN	A	157.7.205.20

;; Query time: 78 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Sep 17 13:15:13 2015
;; MSG SIZE  rcvd: 52
```

And I can see [tokyo.pyladies.com](http://tokyo.pyladies.com) just fine!

Let me know if there's anything else I can do.
