### ISSUE TITLE
Add PyCon 2016 PyLadies info and Update speaking resources

### ISSUE THREAD

**Issue by willingc** [pyladies/pyladies#223]
It would be great to:
- [ ] draft a post on PyCon 2016
- [ ] update how to submit a talk, tutorial, or poster proposal
- [ ] perhaps have encouraging guest posts by folks that have attended past PyCons

**Comment by econchick** [comment]
+100000000

Perhaps solicit on the org list?

**Comment by willingc** [comment]
Closing this after a very fun, successful PyCon 2016. We can open new issues for PyCon 2017.
