### ISSUE TITLE
Add PyCon 2017 dates to /resources when released

### ISSUE THREAD

**Issue by williln** [pyladies/pyladies#274]
http://www.pyladies.com/resources/

Currently, the 2015 dates are displayed. 
<img width="730" alt="screen shot 2016-06-06 at 6 23 36 pm" src="https://cloud.githubusercontent.com/assets/2286304/15843055/ca575d5e-2c13-11e6-9856-6b7b506f47b0.png">

**Comment by econchick** [comment]
@williln I welcome a PR for this :)

**Comment by williln** [comment]
@econchick Was hoping a newbie-newbie would pick this up! But I can submit a PR next week :)

**Comment by daminisatya** [comment]
@willingc @econchick @williln  Can I work on this? :)

**Comment by willingc** [comment]
Go for it @daminisatya 👍

**Comment by daminisatya** [comment]
@willingc Looks like the conference has closed the dates for sending proposals, should we wait and change to 2018 once announced? or change it with the current available dates?

**Comment by willingc** [comment]
I think either option is fine. If you want practice on PRs, please feel free to update the dates and link for 2017. :sunflower:
