### ISSUE TITLE
New repo requested

### ISSUE THREAD

**Issue by willingc** [pyladies/pyladies#275]
@econchick @audreyr @estherbester @jackiekazil I'm not sure who exactly, other than Lynn, has the super powers to create a pyladies-maintainers repo for me. I would also like a mailing list with the same name unless someone has a better suggestion.

I would use the repo to move resources that are useful to pyladies who are project maintainers and project core developers as well as those looking to become CPython core developers. While the immediate need is a place to put mentorship resources for pyladies wishing to become CPython core devs, I really would like to see the repo used for resources that support and foster women to start their own projects as well.

Help. Pretty please ;-)

**Comment by estherbester** [comment]
I'll create the repo, @willingc! As for a mailing list, you should create it using google groups, maybe add one more person to help you administrate? 
 
Also, we should probably refresh our Github team settings at some point..

**Comment by willingc** [comment]
@estherbester Thanks! Good idea on the additional administrator(s).

**Comment by willingc** [comment]
Thanks @estherbester. Closing the issue.
