### ISSUE TITLE
Set DNS for melbourne.pyladies.com to point to github pages

### ISSUE THREAD

**Issue by pfctdayelise** [pyladies/pyladies#282]
I've set up the website using github pages, at pyladiesmelbourne.github.io ([Repo](https://github.com/pyladiesmelbourne/pyladiesmelbourne.github.io)) 
(and CNAME so clicking on the github.io url won't do anything now)

Next some DNS magic is needed on your side: https://help.github.com/articles/setting-up-a-custom-subdomain/

thanks!

**Comment by econchick** [comment]
Ok - I just setup DNS to point to pyladiesmelbourne.github.io. Let me know if it doesn't work in ~24 hours (takes a while for DNS to propogate).
