### ISSUE TITLE
Contact button is broken

### ISSUE THREAD

**Issue by daminisatya** [pyladies/pyladies#306]
When clicked on the "Contact" button, no action is observed. 

![image](https://cloud.githubusercontent.com/assets/6227784/25710192/2a6651fa-3109-11e7-8fdd-52851f4ac18b.png)

**Comment by izaguerreiro** [comment]
Hi @daminisatya 
When you click the contact button it opens the window of your email client, in my case I use Ubuntu opens Thunderbird. You may not have an email client installed on your computer.

**Comment by estherbester** [comment]
Confirmed the link works as a `mail ref`, and should open an email client. Closing this one!
