### ISSUE TITLE
"Get your mac ready for Python Programming" page links should be updated

### ISSUE THREAD

**Issue by estherbester** [pyladies/pyladies#309]
Some of the links on this page are now out of date: http://www.pyladies.com/blog/Get-Your-Mac-Ready-for-Python-Programming/

**Comment by lgh2** [comment]
I was setting up my environment on a new computer and this blog post is one of the top results for installing `pip` on a Mac. The link that it points to install `pip` looks really sketchy, and I don't think it's owned by the PSF. 
This is the documentation from PyPA, which we should probably link to: https://pip.pypa.io/en/stable/installing/
This is the correct link to get with `curl`: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

If I have time I will try to make a PR for this.
