### ISSUE TITLE
help with mynt  installation

### ISSUE THREAD

**Issue by photon-e** [pyladies/pyladies#344]
please i need help with mynt it keeps asking me to install c++ and i have install it multiple times .....it still doesn't solve the problem

**Comment by willingc** [comment]
If you are using Python 3, try:

`python3 -m pip install mynt`

If that doesn't work, please let me know.

**Comment by photon-e** [comment]
I did, it still didn't work....can I use Jekyll instead

**Comment by willingc** [comment]
@photon-e Are you trying to work on the PyLadies website, a local PyLadies site, or another Mynt project?

**Comment by photon-e** [comment]
no, i am trying to create another Mynt project from the tutorials on the Pyladies website.

**Comment by willingc** [comment]
Hi @photon-e, I'm going to suggest asking the Mynt maintainer if you wish to install Mynt. If you are looking for a Python static site generator, Pelican and Nikola are two popular ones.
