### ISSUE TITLE
kit.pyladies.com is wrongly configured

### ISSUE THREAD

**Issue by tanvibhakta** [pyladies/pyladies#347]
The Readme.md file asks us to look at the nicely formatted kit at kit.pyladies.org

This domain is broken because it hasn't been properly formatted on CloudFare.

I have also filed this issue on https://github.com/pyladies/pyladies-kit/issues/46

<img width="1280" alt="screen shot 2018-10-08 at 12 27 07 pm" src="https://user-images.githubusercontent.com/13763558/46595448-020d6d00-caf6-11e8-824a-236b60c1b48d.png">

**Comment by pfctdayelise** [comment]
Seems fixed now.

**Comment by willingc** [comment]
Verifying its back up now.
