### ISSUE TITLE
Set DNS for to tokyo.pyladies.com to point to github pages

### ISSUE THREAD

**Issue by okusama27** [pyladies/pyladies#357]
I changed our web site  using github pages of PyLadies Tokyo Web Page.

https://pyladiestokyo.github.io

Could you set up the forwarding destination of subdomain( tokyo.pyladies.com ) of PyLadies Tokyo?

Old ask ticket #221

**Comment by willingc** [comment]
Hi @estherbester and @econchick, Do you have time to add the subdomain on the PyLadies site? If not, I would be happy to do so but would need the credentials :smile:

**Comment by Mariatta** [comment]
@ewdurbin wondering if this is something you can help with? We'd like to have tokyo.pyladies.com subdomain that points to pyladiestokyo.github.io

Thanks.

**Comment by ewdurbin** [comment]
I don't believe that anyone on the PSF team has access to pyladies.com DNS, it is currently delegated to CloudFlare name servers. I'm assuming managed by someone on the PyLadies team.

The pyladies.org domain DNS is hosted by the PSF, though no record exist aside from those for mail and a redirect to pyladies.com.

**Comment by Mariatta** [comment]
Hmm I also don't know how to set this up. @econchick would you have time to look into this?

**Comment by econchick** [comment]
Hey there - I've added `tokyo.pyladies.com` to our DNS to point to `pyladiestokyo.github.io`. @okusama27 you'll need to do steps 1 - 3 from [these docs](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain) to get it working. 

Ping me if it doesn't work!

**Comment by okusama27** [comment]
Thank you for letting me it.
Sorry, I missed comments.
We set it and We can look PyLadies Tokyo page on  http://tokyo.pyladies.com/ .

**Comment by okusama27** [comment]
I close this ticket.
