### ISSUE TITLE
Homebrew installation command doesn't work on website

### ISSUE THREAD

**Issue by phranzia** [pyladies/pyladies#358]
On this page, the link to install Homebrew doesn't work.
```
$ ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
```
But the correct link is in the code.
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
This is the page I'm referring to: https://www.pyladies.com/blog/Get-Your-Mac-Ready-for-Python-Programming/Get-Your-Mac-Ready-for-Python-Programming/

**Comment by willingc** [comment]
You are correct @phranzia. Thanks for pointing this out. Would you like to make a Pull Request to add the correct link?

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

**Comment by willingc** [comment]
Closing since the 2018 revision of the resource mentions the corrected link.

<img width="646" alt="Screenshot 2019-05-20 16 45 52" src="https://user-images.githubusercontent.com/2680980/58058708-c5d7cb80-7b1e-11e9-8339-99e288f0f491.png">
