### ISSUE TITLE
Add PyLadies Remote to Locations

### ISSUE THREAD

**Issue by willingc** [pyladies/pyladies#365]
Add Remote to the list of locations. http://remote.pyladies.com

**Comment by andressavldrs** [comment]
Can I take this issue? :)

**Comment by lorenanicole** [comment]
@andressavldrs if you'd like to work on it we have a Sat June 20th hack scheduled. See in the PyLadies Slack in the #project-tech-infra channel.

**Comment by Mariatta** [comment]
Closed via #483
