### ISSUE TITLE
can we haz our donation page?

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#37]
https://psfmember.org/civicrm/contribute/transact?reset=1&id=6

**Comment by econchick** [comment]
To revive this old discussion, I think we should resurrect the `sponsor` page.  Perhaps a `How I can get involved` with links to subpages to `Sponsor`, `Donate`,  `Start your own PyLadies`, `Find a Local PyLadies`

**Comment by pushplataranjan** [comment]
@estherbester @econchick If this issue is resolved. kindly close the issue. I found there are a lot of open issues and PR.
If i can do anything to close issues and review PR, please give a heads up.

**Comment by willingc** [comment]
Let's add a donate button or link to donate during website refactor.
