### ISSUE TITLE
Add a Code of Conduct file to root directory

### ISSUE THREAD

**Issue by willingc** [pyladies/pyladies#386]
It would be nice to make these (COC, Issue template, PR template) green 👍 
<img width="761" alt="Screenshot 2019-05-07 13 06 54" src="https://user-images.githubusercontent.com/2680980/57329683-2b609c80-70c9-11e9-999d-076bf2013609.png">

**Comment by andressavldrs** [comment]
I just made a PR to solve this issue, let me know if it is all right :)

**Comment by willingc** [comment]
Closed by #424
