### ISSUE TITLE
Add "how to join slack" on About page

### ISSUE THREAD

**Issue by willingc** [pyladies/pyladies#390]
Let's add how to join the pyladies slack to the About page
https://www.pyladies.com/about/

**Comment by willingc** [comment]
Link to invite: https://slackin.pyladies.com/

**Comment by amnoweb** [comment]
I can take this!

**Comment by Mariatta** [comment]
Yes, please create a PR @amnoweb

**Comment by willingc** [comment]
Hi @amnoweb. Please let me know if you need any help with the issue.
