### ISSUE TITLE
Update PyLadies locations using the PyLadies organizers spreadsheet

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/pyladies#392]
@econchick has provided me with a PyLadies organizers spreadsheet, I can easily automate adding chapter info using that.

Will use this issue to propose how to do this more. 

/cc @willingc

**Comment by willingc** [comment]
Just made a PR #394 that fleshes out the dev setup and notes on YAML for location info.

**Comment by willingc** [comment]
#396 related to this issue. 

#394 has merged.
