### ISSUE TITLE
Add a Funding button to the GitHub repo

### ISSUE THREAD

**Issue by willingc** [pyladies/pyladies#395]
GitHub enables one to put a funding button on repos for sponsorship donations. We should consider doing so: https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization.

cc/ @lorenanicole

**Comment by lorenanicole** [comment]
YES! :100:!

**Comment by Mariatta** [comment]
I've created [FUNDING.yml](https://github.com/pyladies/.github/blob/master/FUNDING.yml), linking it to https://psfmember.org/civicrm/contribute/transact?reset=1&id=6
(the same link found in https://www.pyladies.com/sponsor/)

I've also enabled the Sponsors feature under pyladies/pyladies
![Screen Shot 2019-06-04 at 5 43 55 PM](https://user-images.githubusercontent.com/5844587/58922573-5eaa4180-86f0-11e9-81f5-bf2125ef47b0.png)

**Comment by willingc** [comment]
Going to close. Thanks @Mariatta :heart:
