### ISSUE TITLE
Update meetup app for API changes

### ISSUE THREAD

**Issue by willingc** [pyladies/pyladies#405]
Meetup is changing its API access. We may need to update the app on the homepage.

> This is a reminder that Meetup is changing its API access and that you have until August 15, 2019 to update your integration.

**Comment by Mariatta** [comment]
I went through the meetup widget js code, and at the moment there is security issue because meetup API keys are exposed and committed to this public repo. I would consider this high priority to be looked into.

**Comment by willingc** [comment]
Looks like OAuth2 is now the preferred method to authenticate: https://www.meetup.com/meetup_api/auth/#oauth2

**Comment by willingc** [comment]
Priority of this issue is raised since it is past the 8-15 and it looks as if the meetups are no longer displaying.

**Comment by Mariatta** [comment]
Reopening since this is not addressed yet.

**Comment by ks--ks** [comment]
Looking into it.

**Comment by ks--ks** [comment]
Here is the update: 
1. To fix the events widget, we must have authentication with OAuth2.
2. To be eligible for this authentication, the request must be made from (1) an administrator of the PyLadies network or (2) from someone who has a Meetup Pro subscription. I can get one and request the authentication if this is a good way to go. Please let me know.

**Comment by ks--ks** [comment]
Working on a solution that would cash PyLadies rmeetup.com into an intermediate location and feed the data into the website.
