### ISSUE TITLE
Improve PyLadies map, allow lookup by region

### ISSUE THREAD

**Issue by Mariatta** [pyladies/pyladies#412]
In [PyLadies locations page](https://www.pyladies.com/locations/), we can see a map of known PyLadies chapters, as well as a list of all chapters alphabetically by city name.

I think it would be great to improve the map that can allow filtering/searching by Country, or by Region, or by state. For example, people might want to search for "PyLadies in Southeast Asia" or "PyLadies in USA" or "PyLadies in Eastern Europe". 

It can also be great to be able to filter for other properties, such as "which PyLadies have meetup" or "twitter acct" or "website", etc.

**Comment by kabahima** [comment]
I would like to work on this issue

**Comment by ks--ks** [comment]
Is someone working on this item?

**Comment by lorenanicole** [comment]
@ks--ks not actively, if you want to try your hand at it the relevant info about how to develop and work locally can be found in the README.md

**Comment by lorenanicole** [comment]
I've started working on this here: https://github.com/pyladies/pyladies/pull/526

**Comment by BethanyG** [comment]
Adding in some links from a Slack discussion:

-  Mapbox and Mabox Search APIs:  https://docs.mapbox.com/api/search/
-  [Folium](https://python-visualization.github.io/folium/)  & [Leaflet](https://leafletjs.com/)
-  [Open Street Maps](https://www.openstreetmap.org/#map=4/38.01/-95.84) & [Related Search Engine Services](https://wiki.openstreetmap.org/wiki/Search_engines#Search_engine_services)
- [Nomantium](https://nominatim.openstreetmap.org/)

**Comment by BethanyG** [comment]
@lorenanicole - I would love to help with this, if I can.

**Comment by BethanyG** [comment]
I think having each point be that chapters logo would be awesome....at least where we have the logos available as SVG.
