### ISSUE TITLE
blog.pyladies.com view not showing latest blog posts

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/pyladies#416]
The blog.pyladies.com view is out of sync with the most recent blog posts showing on pyladies.com .

Here's screen shot of pyladies.com:
![image](https://user-images.githubusercontent.com/4573607/63114947-c2a47e00-bf5b-11e9-85f0-2aabafae9ba3.png)

And blog.pyladies.com:
![image](https://user-images.githubusercontent.com/4573607/63114961-cc2de600-bf5b-11e9-8e9a-549dfdff81da.png)

**Comment by Mariatta** [comment]
Oh I wonder if it is pointing to https://github.com/pyladies/pyladies-blog which we archived because of duplication.

**Comment by lorenanicole** [comment]
I'm sure we can fix that ... may as well just have it point to ... what's actually in the `_posts` folder eh?

**Comment by willingc** [comment]
This looks as if it is now redirecting to the correct location.
