### ISSUE TITLE
Retaining women in open source: Organising open source day monthly 

### ISSUE THREAD

**Issue by tapaswenipathak** [pyladies/pyladies#421]
Hi folks: Finding an active open source contributor or maintainer woman is hard. Internships give a break in open source, if observed there is no retention of women in open source and research[1] suggests. Implementing open source day per month letting women work with mentor and contribute in an open source project they would like would be practical implementation than just publishing research and articles. Lemme know if you would interested in supporting and I will share further things.

[1] https://en.wikipedia.org/wiki/Diversity_in_open-source_software

**Comment by lorenanicole** [comment]
Could you elaborate on what it is you are specifically looking for? For example - one thought for me may be with the proposed future PyLadies governance model we'd have a tech pillar that oversees maintaining things like pyladies.com and our resources here on github. See: https://github.com/pyladies/global-organizing/issues/11. Would joining that project team and working on our backlog be an example of something you are interested in? Or are you looking for someone to more squarely be a maintainer on a project (e.g. requests let's say) and mentor you?

**Comment by tapaswenipathak** [comment]
On Wed, 4 Sep 2019, 01:18 Lorena Mesa, <notifications@github.com> wrote:

> Could you elaborate on what it is you are specifically looking for? For
> example - one thought for me may be with the proposed future PyLadies
> governance model we'd have a tech pillar that oversees maintaining things
> like pyladies.com and our resources here on github. See:
> pyladies/global-organizing#11
> <https://github.com/pyladies/global-organizing/issues/11>. Would joining
> that project team and working on our backlog be an example of something you
> are interested in? Or are you looking for someone to more squarely be a
> maintainer on a project (e.g. requests let's say) and mentor you?
>

Hello, I would be happy helping pyladies/global-organizing#11
<https://github.com/pyladies/global-organizing/issues/11>. I will email the
proposal out.
