### ISSUE TITLE
Help with Pyladies Rio website

### ISSUE THREAD

**Issue by biancarosa** [pyladies/pyladies#436]
Hey :)

We're struggling to get our Pyladies Rio back (rio.pyladies.com)
The website is hosted on Github pages (https://github.com/PyLadiesRio/PyladiesRio.github.io) with the custom domain correctly set up:

<img width="695" alt="Screen Shot 2019-11-06 at 16 35 20" src="https://user-images.githubusercontent.com/1480558/68331268-79c01980-00b3-11ea-83ce-0265e2de369e.png">

I suppose it has something to do with the domain configuration.

**Comment by econchick** [comment]
Hey there - I just created the DNS entry for you. I can see that it's working, but it may take a few hours to propagate everywhere. Feel free to re-open this issue if you don't see rio.pyladies.com working in 24 hours.

Thanks!
