### ISSUE TITLE
Adding a CODEOWNERS file

### ISSUE THREAD

**Issue by jtemporal** [pyladies/pyladies#459]
Should we create a `CODEOWNERS` file and add the @pyladies/tech-and-infra-admins handles into that file?

Adding this file would help to tag reviewers to new pull requests automatically.

I'm afraid this might overcrowd our e-mail inboxes, but it seems to be a good idea as a reminder for pull request reviewing.

Any thoughts on that?

**Comment by lorenanicole** [comment]
@jtemporal that makes sense to me. That being said, the @pyladies/tech-and-infra-admins should be only those with merge powers (and I think we intentionally need to keep this a smaller group to start). I think it may be appropriate for us to make a @pyladies/tech-and-infra which is for contributing members, and they can review.

Additionally all PRs we ought to use a PR template too. Which we can use the group alias in the `assignees`.

**Comment by lorenanicole** [comment]
Added in with https://github.com/pyladies/pyladies/blob/master/.github/CODEOWNERS
