### ISSUE TITLE
Update Social Media Links on Pyladies Website

### ISSUE THREAD

**Issue by albendz** [pyladies/pyladies#474]
# Summary
Update the social media links at the footer of the Pyladies website

# Details
![pyladiessocial](https://user-images.githubusercontent.com/12453997/80320190-ec988a80-87e2-11ea-8a88-9828ae2897b4.PNG)

* Remove Google+
* Add YouTube channel https://www.youtube.com/PyLadies
* Add slack https://slackin.pyladies.com
* Add twitter https://twitter.com/pyladies
* Add Instagram https://www.instagram.com/pyladies_global/

**To do**: 
- [x] Facebook: and figure out who own PyLadies Facebook and how to get access to it https://www.facebook.com/pyladies
- [x] LinkedIn: there is a PyLadies group, who manages it? is this active? https://www.linkedin.com/groups/3984711/

For the included screenshot, this needs to be updated: https://github.com/pyladies/pyladies/blob/f95804a1f1e856e23c14023d221ea1dfe73e93d7/www/_templates/site.html#L85

Some of the other pages probably need to be updated to like this one:
https://github.com/pyladies/pyladies/blob/master/www/_templates/layout.html#L19

# Interested in working on the issue?
Yes, happy to work on this issue. Documentation here is a bit out of date for requesting access: https://github.com/pyladies/pyladies/blob/master/CONTRIBUTING.md#contributing-to-the-pyladies-repo

**Comment by albendz** [comment]
Confirmed with @Mariatta I will pick this up and work on it

**Comment by albendz** [comment]
Interesting problem: The site can only be built with Python2. I'm working on another issue #475 to look into other implementations. What I'm thinking is that it would be a reasonable path to migrate this to a more modern static site generator like Pelican rather than maintain it in Python2. Part of it is that we want to do this anyway and the other part is me not wanting to have two versions of Python in my development environment.

Any thoughts here? If there is enough work we want to do on the site, I can invest in Python2 management. If we really just want to move to another site, I can close this and focus more on setting up a new site.

**Comment by Mariatta** [comment]
I think let's not bother trying to maintain a Python 2 version. It would be great to make it work with modern Python framework.

**Comment by albendz** [comment]
That's what it seems like. It would be ideal if we choose a similar Python3 static site generator for #475 so I will see what we decide on there. If not, then I can work on porting the Pyladies site to something newer.

**Comment by ks--ks** [comment]
Is this issue still open? I am interested in picking it up.

**Comment by reshamas** [comment]
@albendz can we add Instagram to list:
https://www.instagram.com/pyladies_global/

To do:  figure out how to get access to this FB page:
https://www.facebook.com/pyladies

**Comment by reshamas** [comment]
add LinkedIn group:
https://www.linkedin.com/groups/3984711/

Audrey Feldroy and Esther Nam are admins for this

**Comment by Marie-L** [comment]
**Next steps:**:
1. understand how [Entypo](http://www.entypo.com/) is used
2. find icon IDs for slack, instagram, stackover flow, you tube and use within link

**Comment by lorenanicole** [comment]
I've been added to PyLadies Facebook group. We have the additional:

- Slack - slackin.pyladies.com
- Instagram - https://www.instagram.com/pyladies_global/

**Comment by lorenanicole** [comment]
OK I added in all the social media things, lol, we can decide which to keep or remove:

![image](https://user-images.githubusercontent.com/4573607/86404120-a513fc00-bc74-11ea-95fb-110a2cf4bf5c.png)

Also I removed entypo as the data font, and instead made a collection on icomood.

**Comment by lorenanicole** [comment]
Closing this issue out as it has been updated.
