### ISSUE TITLE
[Spike] Investigate Options To Build Pyladies Blog

### ISSUE THREAD

**Issue by albendz** [pyladies/pyladies#475]
# What
Research different ways to implement a new Pyladies blog. A few options suggested:
* Build with fullstack option (ex. Django)
* Submit posts on existing blog platform (ex. Medium)
* Host with GitHub/Pelican
* Other?

Related to the Pyladies/Project-Communications project Issue: https://github.com/pyladies/project-communications/issues/1

# Done When...
This task is done when:
* There is a description of feature needed for the blog
* Each option is investigated with pros, cons, and pricing

# Other notes
* Prefer free options
* Can create accounts with a shared email address (would need to be created)
* There are designers in the community to cover re-skinning or providing graphics for the site
* Consider multi-lingual support for site and translated blog posts

# Interested In Working On This Issue?
Yes, I will work on this issue.

cc: @lorenanicole

**Comment by albendz** [comment]
Current website/blog:
* Similar to Pelican where there are a mix of markdown and html files that are converted into assets for a static site
* Based on Python2 libraries unavailable in Python3
*  All posts and content are in GitHub and are review via PRs

**Comment by albendz** [comment]
Pelican:
* This would be most similar to the existing blog - we could do reuse more easily because it also converts html and markdown into static content. Probably some pre-existing experience with this in the community
* Can reuse the already documented contribution flow
* Can be hosted in GitHub

**Comment by albendz** [comment]
Medium:
* Does not cost to post blogs
* Readers will experience ads
* Potential for revenue from readers who have a Medium membership if we use the partner program (could be an opportunity to invite users to read on Medium and like to support? - I'm thinking this isn't really the type of culture we want)

**Comment by albendz** [comment]
Wordpress:
* We will have to pay annually to have a particular domain
* If individuals want to be authors on the posts, they will need to create an account and it seems like it will be a bit of a pain to onboard every author into the account
* There is a way for people to submit blog posts for review but lots of manual maintenance of admins

**Comment by albendz** [comment]
# Recommended: Static Site Generator (Ex. Pelican)
## Pros
* Simplest solution
* No ads
* Manage through GitHub - keeping inline with other Pyladies projects
* Easier to port over old blog content
## Cons
* Limited as a static site

# Wordpress/Medium
# Pros
* Discovery - people reading other tech blogs will organically find ours
* Some opportunities to generate revenue - this doesn't seem like a goal for us so it's not much of a Pro
# Cons
* Ads  - There isn't really a way to get rid of them even by paying. I think it would be better not to have ads.
* Less flexible than static site generation though there is some customizability
* More work to manage writers and review - additional accounts for authors and approvers, centralized
* Not a bit risk but a factor: The company (Wordpress, Medium) can take down posts or ban accounts (not that this is likely to happen) which is not a problem if we have our own platform

# Build Blog "From Scratch"
After seeing how easy the static site generation would be to set up, build a Flask or Django service and having to maintain a data store seemed really excessive in terms of time, complexity, and maintainability. It also requires a design of review pipeline and managing users. Too costly overall.

If we wanted to do more with a site like having sub-sites for hackathons, coding classes/workshops, forums, etc. then it might be worth it but we have other solutions for those.

**Comment by albendz** [comment]
Discussion welcome - please comment with experience with  any of these solutions, anything I missed, or different perspectives on the points I've made.

**Comment by albendz** [comment]
Some assumptions that affected my recommendation:
* We are more interested in a high quality (i.e. no random ads) community vs. global discoverability
* Easy and well known is better than highly customizable
* We want full ownership of our content and it's management

**Comment by Mariatta** [comment]
No from me on Medium. I don't like the idea that our blog posts to be behind some subscription wall. 
Also no Wordpress. Similar reason, it costs money with little added benefit.

**Comment by lorenanicole** [comment]
Here's my thought:

- Use netlify and setup a pelican theme https://github.com/netlify-templates/pelican-netlify-cms

Netlify has 300 free minutes a month for builds. Also, do we have a contact at Netlify? I imagine maybe I can find one ...

**Comment by willingc** [comment]
Pelican and deploy using Netlify or Zeit works for me. Agree with @Mariatta re: passing on using Medium.

Let's just go with Pelican and move forward on this :smile:

**Comment by albendz** [comment]
For next steps, where do we want this new site to live? Or add it to this project?

**Comment by BethanyG** [comment]
@Marie-L  - rather than Medium, how about [Dev.to](https://dev.to/)?   -- Or rather, the Pelican solution mentioned by @lorenanicole & @willingc above for the full-fledged blog, and re-posting/cross-posting on Dev.to.  We could maybe do shorter things in one spot, and longer-form in another.

**Comment by Marie-L** [comment]
@BethanyG yeah Dev.to seems like a good option, thanks for the suggestion 😊 - but if most people are in favour of Pelican then I'll go along with that

**Comment by ks--ks** [comment]
Maybe this will be an option to use? 
https://www.staticgen.com/

**Comment by lorenanicole** [comment]
https://github.com/netlify-templates/pelican-netlify-cms

**Comment by lorenanicole** [comment]
@albendz to our discussion of how can we provide folks to work on chapters blog we need to figure out how to dismantle the entire monolith, my suggestion is to create a working doc on how we start this and what takes priority such as:

1. Start blog.pyladies.com - a new home for the Global Pyladies blog
2. Provide submodules in the main repo to organizer chapters to do their own website stuff 

For more on submodules: https://github.blog/2016-02-01-working-with-submodules/

**Comment by albendz** [comment]
@ks--ks For the static generators you shared, Pelican uses some of the underlying libraries there... so we'd be using it indirectly

**Comment by lorenanicole** [comment]
bumping to keep fresh
