### ISSUE TITLE
Remove `master` as name of default branch

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/pyladies#480]
# Scope

GitHub has allowed for tooling to rename your default branch. In accordance with this, PyLadies will be updating the name of our default branch to `main`. 

## Work to be done

- [ ] Update default name in settings
- [ ] Confirm name change doesn't impact any CI/CD for website

**Comment by Mariatta** [comment]
I have tried doing this for my personal repo, so I can share the steps and checklist:

On the command line:
```
git branch -m master main
git push origin main
```

On GitHub repo settings > Branches
[ ] change the default ``name`` to ``main``
[ ] update the branch protection rules if there is any on the ``master`` branch, add those to `main`. 
[ ] update CI rules e.g. travis ci yaml files etc that references master branch
[ ] update Pull requests that want to merge to ``master``, to ``main``. or close them
[ ] once PRs referencing ``master`` have been closed/updated, ``master`` branch can be deleted.

**Comment by Mariatta** [comment]
Other consideration: GitHub pages seems to be hardcoded to use `master` from GitHub side. We cannot build GitHub pages unless we have `master` branch. Perhaps not an issue for pyladies/pyladies repo.

**Comment by lorenanicole** [comment]
@econchick we are going to need your help with the below as I don't have the user login info to update this 👇 

> In readthedocs:

> Go to projects > Advanced settings > Global settings
> change the default branch to main.

**Comment by lorenanicole** [comment]
> Other consideration: GitHub pages seems to be hardcoded to use `master` from GitHub side. We cannot build GitHub pages unless we have `master` branch. Perhaps not an issue for pyladies/pyladies repo.

Ah yes. We are using `elections.pyladies.com` for the GitHub pages. We will cross that bridge as we need.

**Comment by lorenanicole** [comment]
This is now default using `main` and builds from netlify as such.
