### ISSUE TITLE
PyLadies Website  2.0 Migration

### ISSUE THREAD

**Issue by albendz** [pyladies/pyladies#482]
Rebuilding the Pyladies blog will require breakup up what we have in the current repo and determining what needs to be moved into the new blog.

**First task:** How do we manage issues across https://github.com/pyladies/pyladies and https://github.com/albendz/project-communications

Some open questions to discuss:
What infrastructure changes will we need? New repos, admin, CICD
We need documentation on what is currently hosted in the repo: blog posts, assets, chapter specific content, documentation
For each entity in the repo, where should it go in the  future?
What is the initial v1 scope for website 2.0?
What tech should we use for website 2.0?
What does release look like? Start with new content only, backfill old content, what pages should be available first?
Move blog and content publishing related content to the comms project?
Define what belongs in the comms project vs. the pyladies blog hosting repo
Process  on how chapters can add new content

Comms linked Issue:
https://github.com/pyladies/project-communications/issues/54

**Comment by albendz** [comment]
@Mariatta Could you add the June 2020 hack label to this?

**Comment by albendz** [comment]
Related: https://github.com/pyladies/pyladies/issues/475

**Comment by lorenanicole** [comment]
Update:

-  github.com/pyladies/chapter-websites repo has been created to help port over websites from this repo 
- website is now using netlify for preview CI build step
- website now hosted on github pages via `gh-pages` branch
