### ISSUE TITLE
Setup Netlify for PyLadies website

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/pyladies#488]
# Overview

Netlify is an awesome CI/CD tool and we should use it!

## Work to be done

- [x] Fill out netlify for free tooling as open source project
- [x] Add netlify to repo
- [x] Add netlify badge to website
- [x] Configure netlify deploy steps
- [x] Open PR confirm netlify deploy preview works
- [x] Confirm netlify free account!
- [x] Invite @pyladies/tech-and-infra-admins to the netlify team

**Comment by trallard** [comment]
Is this open? I can take care of this if so

**Comment by BethanyG** [comment]
I think @lorenanicole made a lot of progress on this during the hack weekend, but there may be additional items.  I updated with what I remember her completing.

**Comment by lorenanicole** [comment]
Ah yes I got most of this done @trallard I am just waiting for us to get our free open source account setup! 💃

**Comment by trallard** [comment]
Lovely! Let me know if you need help with anything

**Comment by lorenanicole** [comment]
I have the team! I am going to invite folks that are in the @pyladies/tech-and-infra-admins to the account. What I'll need is the emails y'all use for your GitHub account to invite ya. If you don't want to post your email here you can DM in Slack!

**Comment by lorenanicole** [comment]
OK this has been setup. So here's the question, do we just want to cut over and have netlify do all the hosting? I'm going to say _yes_ haha.

**Comment by lorenanicole** [comment]
Done with PR #512
