### ISSUE TITLE
PyLadies website: Clean up the "Forum" page

### ISSUE THREAD

**Issue by Mariatta** [pyladies/pyladies#501]
At the top of pyladies.com website, there is a link to "Forum" that points to discuss.pyladies.com .

That page seems unfinished and does not look consistent.

Not sure what's needed to complete that page. We might even be able to just remove it for now.

**Comment by BethanyG** [comment]
Adding `team:communications` tag as well and pinging @Marie-L, in case this is something the'd like to investigate/design/complete.

**Comment by Mariatta** [comment]
It was reported hat there is `ERR_CERT_DATE_INVALID` error in that page. https://github.com/pyladies/info/issues/6

**Comment by lorenanicole** [comment]
I'm removing this from the website. YOLO! It's dead and takes up prime real estate in the nav bar. CC: @Marie-L

**Comment by lorenanicole** [comment]
PR to remove: https://github.com/pyladies/pyladies/pull/511
