### ISSUE TITLE
Request to Join Project Tech & Infra: ks--ks

### ISSUE THREAD

**Issue by ks--ks** [pyladies/pyladies#502]
**Proposed Team Member Details**

| Name | GitHub Handle | Slack Handle | PyLadies Chapter | Team Role |
|-------|----------------|--------------|-------------------|-----------|
| Olga | ks--ks | Olga | Open for opportunities | support |

**Why do you want to join the Project Tech & Infra team?**
I would love to contribute to PyLadies community. 
/cc @pyladies/pyladies-global-admin @pyladies/tech-and-infra-admins

**Comment by lorenanicole** [comment]
@ks--ks are there are specific issues that you are interested in from the backlog?

**Comment by lorenanicole** [comment]
👋 @ks--ks just bumping the above!

**Comment by ks--ks** [comment]
Sorry for catching up late! Have to fix my notifications. I got access to translations localisations, so all good.
