### ISSUE TITLE
Adjust social media, netlify badge in footer & add social page to website

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/pyladies#514]
# Overview

This ticket included updating the social media icons: https://github.com/pyladies/pyladies/issues/474. So all the social media icons have been added to the footer.

However the layout in the footer is a bit cluttered. Below shows screenshot from desktop, however on mobile it's not as smooth.

![image](https://user-images.githubusercontent.com/4573607/86405564-32585000-bc77-11ea-8b14-5903dabed447.png)

It'd be great to:

- Find a better home for all the social media icons, maybe only show a subset? 
- Add all these to a `pyladies.com/social` page

## Scope of work

*To update the footer:*

This code lives in:
- `www/_templates/site.html` for the html for the footer
- `www/_assets/css/fonts` for the icomoon fonts
- `wwww/_assets/css/screen.css` for the `.icon*` classes 

*To add a new page:*

This code lives in:
- `www/` and would require an additional dir named `social` with an `index.html` setup
- Updated to the navbar in `www/_templates/site.html`

**Comment by lorenanicole** [comment]
@BethanyG this is the ticket I was referring to 😄

**Comment by BethanyG** [comment]
I'll take a shot!  @Marie-L  and I are going to hack on design this weekend.  I'll add this to our list of things to look at.  😁

**Comment by BethanyG** [comment]
Ugh.  This slipped through the tracks and got marked stale.  Will try to tackle this this week (8/2/2020)
