### ISSUE TITLE
Fix broken link in the "Announcement for Registering PyLadies Members" post on the website.

### ISSUE THREAD

**Issue by PluckyPrecious** [pyladies/pyladies#527]
Links to the highlighted words "February 2020 Minutes" "PyLadies Global Interim Admins" and "broader team" are showing 404 Error.

**Comment by Mariatta** [comment]
The links are correct they're just not available unless you're a member of the PyLadies org on GitHub.

**Comment by PluckyPrecious** [comment]
Very well then.
