### ISSUE TITLE
Get Swag Button redirects to https://pyladies.spreadshirt.com/ which is currently unavailable 

### ISSUE THREAD

**Issue by Aashimalik** [pyladies/pyladies#567]
<img width="468" alt="Screenshot 2021-05-29 at 7 51 10 PM" src="https://user-images.githubusercontent.com/29588003/120073722-396e2500-c0b7-11eb-9ce3-261c1f163e5a.png">

When clicked to the `Get Swag` Button it redirects to the unavailable page, I have one proposal if this page is under construction can we add a coming soon page.  Also, I'm interested in working on this feature. 

Waiting for your response.

**Comment by Mariatta** [comment]
Thanks for the report. The correct url is https://shop.spreadshirt.com/pyladies/

If you would like to create the PR for it, it would be welcomed. Thanks.

**Comment by Aashimalik** [comment]
Thanks, @Mariatta!
 I have created the PR here https://github.com/pyladies/pyladies/pull/568.
 
Currently, one check is failing, could you please help me so that I can fix it.
