### ISSUE TITLE
Blog URL is not working

### ISSUE THREAD

**Issue by Aashimalik** [pyladies/pyladies#569]
_This template should be used (edited) for PyLadies members that wish to join the Project Tech & Infra team.

**Proposed Team Member Details**
When clicked on Blogs in the Navigation bar it redirects to `https://blog.pyladies.com/` which is currently unavailable. 

Name | GitHub Handle | Slack Handle | PyLadies Chapter | Team Role 
| Ayesha Malik | AashiMalik  | ayeshamalik8751@gmail.com | 

**Why do you want to join the Project Tech & Infra team?**

/cc @pyladies/pyladies-global-admin @pyladies/tech-and-infra-admins

**Comment by Aashimalik** [comment]
Hi @Mariatta ,

I'm working on a Blog URL fix, Could you please help me in providing the correct URL for the blog tab in the header, currently it redirects to the wrong URL.

Thanks!

**Comment by Mariatta** [comment]
The blog's url is https://pyladies.com/blog/

Thanks.

**Comment by Aashimalik** [comment]
Create the PR here https://github.com/pyladies/pyladies/pull/570.
Please help in merging. Thanks!
