### ISSUE TITLE
Create a TXT record for Pyladies Tokyo

### ISSUE THREAD

**Issue by okusama27** [pyladies/pyladies#577]
Name | GitHub Handle | Slack Handle | PyLadies Chapter | Team Role 
| --| --| --| --|--|
Kameko Ohmura| okusama27| kame-chan | PyLadies Tokyo| staff

Hi.
We use github pages for our web site.
It asked us to create a TXT record in our DNS configuration.
Could you create a new TXT record for the following hostname?

* hostname: `_github-pages-challenge-PyLadiesTokyo.tokyo.pyladies.com`
* value of TXT record: `cc862fd3a9743eaac06dbdd3a015f2`

It asked us to do that work within 7 days.
If you will not be able to do within 7days, I want to do it.
Thank you so much for your help in advance.

**Comment by econchick** [comment]
Sure thing! I've set it up just now - it may take up to 24 hours to propagate, but I do see the record when I query for it:

```sh
$ dig +short -t TXT _github-pages-challenge-PyLadiesTokyo.tokyo.pyladies.com
"cc862fd3a9743eaac06dbdd3a015f2"
```

Feel free to re-open if there's anything else!

**Comment by okusama27** [comment]
@econchick Thank you for early response!
Our settings for github pages succeeded.
