### ISSUE TITLE
Org maintenance

### ISSUE THREAD

**Issue by willingc** [pyladies/pyladies#591]
Let's do some deferred maintenance:
- [x] update the security issues
- [x] move all branches default to main (instead of master)
- [ ] enable branch protection
- [x] Update the netlify base image from Ubuntu 16 to more recent LTS

**Comment by BethanyG** [comment]
Give a shout if you'd like help.  😄

**Comment by willingc** [comment]
Hi @BethanyG! If you have access to the netlify account can you please bump the base image?

**Comment by willingc** [comment]
Link to updating the base image: https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239#how-do-i-update-my-build-image-5

**Comment by Mariatta** [comment]
I've updated netlify base image.

What kind of branch protection do we need?

**Comment by willingc** [comment]
I would just protect the main branch for PRs. Thanks @Mariatta

**Comment by Mariatta** [comment]
@willingc it seems like the latest changes weren't getting deployed to pyladies.com, though the previews seem to work.

Any ideas of what could be the issue here?

**Comment by willingc** [comment]
Resolved via Slack and Huddle.
