### ISSUE TITLE
Virtualenv instructions in README.md

### ISSUE THREAD

**Issue by svaksha** [pyladies/pyladies#62]
I wanted to add a link to our [Bangalore mailing list](http://mail.python.org/mailman/listinfo/pyladies-blr) to the [locations page](http://www.pyladies.com/locations/blr/), and came across this line in the [Readme.md](https://github.com/pyladies/pyladies#to-run-locally) file "It is important that when you create your virtualenv, do not create it in the same folder as the code you downloaded." 

That line was confusing as I already have a virtualenv where I create a separate directory/folder for each project (depending on 2.x or 3.x) and _then_ clone the repo with git. So, the order gets reversed as: 3.Create a virtualenv called PyLadies, and then, 2.Clone to your machine. 
However, the Readme instructions seem to suggest otherwise

**Comment by econchick** [comment]
If this still remains an issue, please reopen to discuss.
