### ISSUE TITLE
Dropdown menu in navigation?

### ISSUE THREAD

**Issue by econchick** [pyladies/pyladies#66]
I think it might be a good idea to implement dropdown menus to clean up the Navigation.  For instance, maybe under "About" we have "Locations", "CoC", etc.  

End goal: I want to put up more pages like "Donations", "Sponsorships", etc, and I don't want to crowd the navigation.

**Comment by rimshaakhan** [comment]
Hello @econchick 
I want to work on this issue. Can you please guide me how to get started?
